[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_source = '''
let g:racer_cmd = $HOME . "/.cargo/bin/racer"
let $RUST_SRC_PATH= $HOME . "/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src"
'''
