[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
depends = ['deoplete.nvim']
build = 'bash install.sh'
hook_add = '''
	set hidden
	let g:LanguageClient_serverCommands = {
        \ 'c': ['clangd', '-compile-commands-dir=' . getcwd() . '/build'],
        \ 'cpp': ['clangd', '-compile-commands-dir=' . getcwd() . '/build'],
		\ 'rust': ['rustup', 'run', 'stable', 'rls'],
    \ }
	let g:LanguageClient_hasSnippetSupport = 0

	set completefunc=LanguageClient#complete

    nnoremap K :call LanguageClient#textDocument_hover()<CR>
    nnoremap F :call LanguageClient#textDocument_formatting()<CR>
	
'''

[[plugins]]
repo = 'vim/killersheep'
